// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/create-payment-intent.tsx";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/pay.tsx";
import * as $3 from "./routes/success.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/PayElement.tsx";

const manifest = {
  routes: {
    "./routes/create-payment-intent.tsx": $0,
    "./routes/index.tsx": $1,
    "./routes/pay.tsx": $2,
    "./routes/success.tsx": $3,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/PayElement.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
